# Generated by Django 5.0.3 on 2024-04-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_orderitem_price_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.BooleanField(default=False),
        ),
    ]
