# Generated by Django 5.0.3 on 2024-04-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_compare"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compare",
            options={"verbose_name_plural": "Compare List"},
        ),
    ]
