# Generated by Django 5.0.3 on 2024-04-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_compare_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_img",
            field=models.ImageField(null=True, upload_to="customer_imgs/"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="phone",
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="profile_img",
            field=models.ImageField(null=True, upload_to="school_imgs/"),
        ),
    ]
