# Generated by Django 4.2.9 on 2024-03-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
