# Generated by Django 5.0.3 on 2024-04-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_product_product_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
