# Generated by Django 4.2.9 on 2024-03-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
